# Generated by Django 6.0.6 on 2026-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
